name: myenv
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - pytorch==2.2.0
  - torchvision==0.17.0
  - torchaudio==2.2.0
  - cudatoolkit=11.8
  - pip
  - pip:
    - accelerate==0.27.2
    - aiohttp==3.9.3
    - aiosignal==1.3.1
    - annotated-types==0.6.0
    - anyio==4.3.0
    - asgiref==3.7.2
    - async-timeout==4.0.3
    - attrs==23.2.0
    - backoff==2.2.1
    - bcrypt==4.1.2
    - build==1.0.3
    - cachetools==5.3.2
    - certifi==2024.2.2
    - charset-normalizer==3.3.2
    - chroma-hnswlib==0.7.3
    - chromadb==0.4.22
    - click==8.1.7
    - coloredlogs==15.0.1
    - dataclasses-json==0.6.4
    - datasets==2.17.1
    - deprecated==1.2.14
    - dill==0.3.8
    - docstring-parser==0.15
    - exceptiongroup==1.2.0
    - fastapi==0.109.2
    - filelock==3.13.1
    - flatbuffers==23.5.26
    - frozenlist==1.4.1
    - fsspec[http]==2023.10.0
    - google-auth==2.28.0
    # Additional dependencies from requirements.txt
    - grpcio==1.47.0
    - huggingface-hub==0.9.0
    - idna==3.3
    - importlib-metadata==4.11.3
    - importlib-resources==5.7.1
    - jinja2==3.1.2
    - joblib==1.1.0
    - markdown==3.3.6
    - markupsafe==2.0.1
    - multiprocess==0.70.12.2
    - numpy==1.22.3
    - packaging==21.3
    - pandas==1.4.2
    - protobuf==3.19.4
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.21
    - pydantic==1.9.0
    - pyjwt==2.3.0
    - pymongo==4.1.1
    - pyparsing==3.0.7
    - pytz==2022.1
    - requests==2.27.1
    - rsa==4.8
    - scikit-learn==1.0.2
    - scipy==1.8.0
    - six==1.16.0
    - tensorboard==2.8.0
    - tensorflow==2.8.0
    - tensorflow-estimator==2.8.0
    - termcolor==1.1.0
    - threadpoolctl==3.1.0
    - tokenizers==0.10.3
    - torch==2.2.0
    - tqdm==4.63.0
    - transformers==4.16.2
    - typing-extensions==4.1.1
    - urllib3==1.26.9
    - werkzeug==2.0.3
    - wrapt==1.13.3
    - yarl==1.7.2
    - zipp==3.7.0
